version: '2'
services:
  mysql:
    image: sample_mysql:2.0
    ports:
       - 3306:3306
  
  app_server1:
    image: sample_php:1.0
    ports: 
       - 8081:80
    links:
       - mysql:mysql
    depends_on:
       - mysql

  app_server2:
    image: sample_php:1.0        
    ports:
       - 8082:80
    links:
       - mysql:mysql
    depends_on:
       - mysql
 
  nginx:
    image: sample_nginx:1.0
    ports:
       - 85:80
    depends_on:
       - mysql
       - app_server1
       - app_server2  
